# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [62]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
def check(numbers_x):
  if numbers_x[0]==numbers_x[-1]:
    print("True")
  else:
    print("\n")
    print("False")

print(check(numbers_x))
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False
print(check(numbers_y))

True
None


False
None





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [21]:
#code here
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)
b=np.arange(12,21).reshape(3,3)
print(b)
print("\n")
c=a+b
print("Result of addition is: ",c)
d=a*b
print("\n")
print("Result of product is:",d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]


Result of addition is:  [[12 14 16]
 [18 20 22]
 [24 26 28]]


Result of product is: [[  0  13  28]
 [ 45  64  85]
 [108 133 160]]

# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [49]:
#code here
b=np.arange(0,12)
x=b.reshape(3,4)
print(x)
p=np.arange(12,24)
q=p.reshape(3,4)
print("\n")
print(q)
print("\n")
t=np.hstack((x,q))
print("Horizontally concatenated are: ",t)
print("\n")
v=np.vstack((x,q))
print("vertically concatenated are: ",v)

# print(x)
# a=np.sum(x,axis=0)
# z=np.sum(x,axis=1)
# print("Column wise sum is",a)
# print("\n")
# print("Row wise sum is",z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Horizontally concatenated are:  [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


vertically concatenated are:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

# Lab Task 04


## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

# Lab Task 05

In [75]:
print("           Welcome to estore:")
print("\n")
shopping_cart ={
    'Product': ['Cargo', 'Makeup', 'aqal', 'shame', 'life'],
    'Prices': [2, 3, 4, 5, 6]}
cart = []
flag=True
while flag:
    print(" GET A LIFE, nvm, Available products at our store are as follows:")
    for idx, product in enumerate(shopping_cart['Product'], 1):
        print(str(idx) + ". " + product + " - " + str(shopping_cart['Prices'][idx-1]))
    choice = input("Enter the number corresponding to the product you want to add to the cart (or 'quit' to quit): ")
    if choice.lower() == 'quit':
        break
    choice = int(choice)
    if choice < 1 or choice > len(shopping_cart['Product']):
        print("Invalid choice. Please enter a number within the range.")
        continue
    myprod = shopping_cart['Product'][choice - 1]
    selected_price = shopping_cart['Prices'][choice - 1]
    cart.append((myprod, selected_price))
    print(myprod,"has been added to your cart.")
print("\n")
print("Your Shopping Cart:")
total_price = 0
for item, price in cart:
    print(item,"-",price)
    total_price += price
print("\n")
print("Your total bill is:", total_price,"$")
print("Exitting you, bye.")

           Welcome to estore:


 GET A LIFE, nvm, Available products at our store are as follows:
1. Cargo - 2
2. Makeup - 3
3. aqal - 4
4. shame - 5
5. life - 6
Enter the number corresponding to the product you want to add to the cart (or 'quit' to quit): 4
shame has been added to your cart.
 GET A LIFE, nvm, Available products at our store are as follows:
1. Cargo - 2
2. Makeup - 3
3. aqal - 4
4. shame - 5
5. life - 6
Enter the number corresponding to the product you want to add to the cart (or 'quit' to quit): 1
Cargo has been added to your cart.
 GET A LIFE, nvm, Available products at our store are as follows:
1. Cargo - 2
2. Makeup - 3
3. aqal - 4
4. shame - 5
5. life - 6
Enter the number corresponding to the product you want to add to the cart (or 'quit' to quit): quit


Your Shopping Cart:
shame - 5
Cargo - 2


Your total bill is: 7
Exitting you, bye.


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [60]:
#code here
def classify(emails):
    ie = []
    pe = []
    se = []
    important_keywords = ['urgent', 'important', 'action required']
    promotion_keywords = ['promotion', 'deal', 'discount']
    spam_keywords = ['prize', 'claim now', 'free', 'click here']
    for email in emails:
        l= email.lower()

        if any(keyword in l for keyword in important_keywords):
            ie.append(email)
        elif any(keyword in l for keyword in promotion_keywords):
            pe.append(email)
        elif any(keyword in l for keyword in spam_keywords):
            se.append(email)
    return ie,pe,se
emails = ["Meeting today is very important","Congrats! you recieved a promotion","special offer for you","estore brings you exciting opportunities and deals","click here to earn a gift","you are awarded a prize for fre","urgent action required at place ofincident"]
important, promotions, spam = classify(emails)
print("Important emails are:")
for i in important:
  print(i)
print("\n")
print("Promotional emails are:")
for prm in promotions:
  print(prm)
print("\n")
print("Spam emails are: ")
for ss in spam:
  print(ss)

Important emails are:
Meeting today is very important
urgent action required at place ofincident


Promotional emails are:
Congrats! you recieved a promotion
estore brings you exciting opportunities and deals


Spam emails are:
click here to earn a gift
you are awarded a prize for fre

# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.

In [63]:
#code here
spanish={
    'Thankyou':['Gracias'],
    'friend':['perra'],
    'girl':['chica'],
    'slap':['bofetada'],
    'okay':['bueno'],
    'hi':['ola']
}
flag=True
while flag:
  text=input("Enter an english word: ")
  x=text.lower()
  if x in spanish:
    print("Spanish translation of word is: ",spanish[x])
  elif x=='quit':
    print("Quitting our program")
    break
  else:
    print("Translation of the word is unavailable")

Enter an english word: ola
Translation of the word is unavailable
Enter an english word: hi
Spanish translation of word is:  ['ola']
Enter an english word: slap
Spanish translation of word is:  ['bofetada']
Enter an english word: quit

# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [65]:
import pandas as pd
x=pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
x

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [80]:
s=np.sum(x['Global_Sales'])
print(s)

8920.44

In [94]:
cc = x['NA_Sales'].corr(x['EU_Sales'])
print("Correlation coefficient between NA_Sales and EU_Sales:",cc)

Correlation coefficient between NA_Sales and EU_Sales: 0.7677267483702631

In [84]:

x.loc[x['Global_Sales'].idxmax()]

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [87]:
nu=np.mean(x['NA_Sales'])
ea=np.mean(x['EU_Sales'])
jp=np.mean(x['JP_Sales'])
os=np.mean(x['Other_Sales'])
print("Average NA sales are: ",nu)
print("Average EU sales are: ",ea)
print("Average JP sales are: ",jp)
print("Average Other sales are: ",os)

Average NA sales are:  0.26466742981082064
Average EU sales are:  0.14665200626581515
Average JP sales are:  0.077781660441017
Average Other sales are:  0.0480630196409206

In [91]:
genre_sales = x.groupby('Genre')['Global_Sales'].sum()
top5 = genre_sales.sort_values(ascending=False).head(5)
print("Top 5 most popular game genres based on global sales: ",top5)

Top 5 most popular game genres based on global sales:  Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [89]:
x.tail(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
16590,16593,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

In [92]:
x['Total_Sales'] = x['NA_Sales'] + x['EU_Sales'] + x['JP_Sales'] + x['Other_Sales']
m = x.loc[x['NA_Sales'].idxmax(), 'Genre']
print("Most popular genre in North America is:", m)

Most popular genre in North America is: Sports

In [93]:
platform_sales = x.groupby('Platform')['Global_Sales'].sum()
sorted_platforms = platform_sales.sort_values(ascending=False)
top3 = sorted_platforms[:3]
print("Top 3 gaming platforms with the highest global sales:", top3)

Top 3 gaming platforms with the highest global sales: Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64